### ISSUE TITLE
How to modified my own model to fit a 3-class problem?

### ISSUE THREAD

**Issue by young169** [DCASE-REPO/DESED_task#59]
It gives me an error like:

ValueError: Using a target size (torch.Size([24, 10, 156])) that is different to the input size (torch.Size([24, 3, 156])) is deprecated. Please ensure they have the same size.

I already change the confs/default.yaml's nclass to 3.But the target size still seems to be 10, What else I should do?

**Comment by turpaultn** [comment]
Hi, 
Yeah, you have to change `local/classes_dict` too.
I agree it's not very intuitive we should probably change the code to make it appear in the configuration file since the dataset is there too :)

**Comment by young169** [comment]
> Hi, Yeah, you have to change `local/classes_dict` too. I agree it's not very intuitive we should probably change the code to make it appear in the configuration file since the dataset is there too :)

It works!

**Comment by turpaultn** [comment]
If you don't have the filenames, it is probably because in train_sed.py you changed the validation set and forgot to mention "return_filename=True" like here: 
https://github.com/DCASE-REPO/DESED_task/blob/f0161eb2a6766e3479494ca5e13a208d82a9c168/recipes/dcase2022_task4_baseline/train_sed.py#L156

From

https://github.com/DCASE-REPO/DESED_task/blob/f0161eb2a6766e3479494ca5e13a208d82a9c168/recipes/dcase2022_task4_baseline/train_sed.py#L152-L158

**Comment by turpaultn** [comment]
It seems you got part of your answers @young169 , can we close this issue ?
